<script>
    /** @type {import('./$types').PageData} */
    export let data;
</script>

<div id="main" class="h-screen w-screen p-12 font-mono">
    <div id="a" class="flex flex-col gap-2 pr-4">
        <h3 class="text-3xl font-bold">🦋 Morpho Design Explorer</h3>
        <p>A Design Explorer written to visualize and graph solution sets generated by the ParaGen methodology<super class="align-super text-xs">[<a target="_blank" href="https://pdxscholar.library.pdx.edu/arch_fac/8/" class="text-blue-500">1</a>]</super>.</p>
        <p>To start with, explore any of the project links on the right!</p>
    </div>
    <div id="c" class="text-3xl font-bold">
    </div>
    <div id="b" class="flex flex-col text-2xl">
        <h3 class="text-3xl font-bold">Recents</h3>
        <a href="{data.prefix}/GCGA_20" class="font-semibold text-blue-500">GCGA_20</a>
        <a href="{data.prefix}/GCGA_27" class="font-semibold text-blue-500">GCGA_27</a>
        <a href="{data.prefix}/GCGA_37" class="font-semibold text-blue-500">GCGA_37</a>
        <a href="{data.prefix}/GCGA_39" class="font-semibold text-blue-500">GCGA_39</a>
    </div>
</div>

<style>
    #main {
        display: grid;
        grid-template-columns: 1fr 1fr;
        grid-template-rows: 1fr 1fr;
        grid-template-areas:
            "a b"
            "c b";
    }

    #a {
        grid-area: a;
    }

    #b {
        grid-area: b;
    }

    #c {
        grid-area: c;
    }
</style>